attribute_name =
  ? [\p{IsAlphabetic}\p{IsDigit}_\-\.]{1,64} ? ;

attribute_type =
  "integer-signed" | "integer-unsigned" | "float" ;

header_command_attribute =
  "attribute" , attribute_name , attribute_type , integer-unsigned , integer-unsigned ;
